### ISSUE TITLE
Jump selecting

### ISSUE THREAD

**Issue by vamolessa** [mbnuqw/jumpt#1]
Nice extension! It's the best one I've tried for this kind of navigation!
However, to really be perfect, it'd need a jump with selection. It would select text from current cursor position to the jump final position.

Some other extension that does this: https://marketplace.visualstudio.com/items?itemName=tranhl.find-then-jump

Thanks!

**Comment by mbnuqw** [comment]
Added in v1.1.0
```json
  {
    "key": "...",
    "command": "extension.jumpt",
    "args": { "select": true }
  },
```
